source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

inhibit_all_warnings!

#platform :ios, '9.0'
#use_frameworks!

target 'EYDouYin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

#   Pods for EYDouYin
#pod 'AlicloudHTTPDNS', '~> 1.6.11'
pod 'ZFPlayer', '3.1.5'
pod 'ZFPlayer/ControlView', '~> 3.0'
pod 'ZFPlayer/AVPlayer', '~> 3.0'
#pod 'ZFPlayer/ijkplayer', '~> 3.0'

#pod 'MPMoviePlayerController-Subtitles', '~> 2.2.2'

#pod 'IJKMediaFramework', '~> 0.1.1'

pod 'AFNetworking', '3.2.1'         #网络请求
pod 'IQKeyboardManager', '~> 6.2.0' #键盘管理
pod 'SVProgressHUD', '~> 2.2.5'     #提示框
pod 'YYModel', '1.0.4'              #字典转模型
pod 'YYCategories', '1.0.4'         #分类
pod 'YYCache', '1.0.4'              #缓存
pod 'MJRefresh', '3.1.15.7'         #刷新
pod 'MJExtension', '3.0.15.1'       #字典转模型
pod 'pop', '1.0.10'                 #动画
pod 'SDWebImage', '~> 5.0.0-beta5'  #图片缓存
pod 'GKNavigationBarViewController', '~> 2.1.2' #抖音的左滑 push 效果
pod 'SJVideoPlayer', '~> 2.1.6'     #播放器
pod 'Bugly', '2.5.0'                #Bugly

end
