name: my_flutter
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5

  #日历
  flutter_datetime_picker: 1.5.1

  #是否是模拟器
  safe_device: 1.1.4

  #轮播图
  flutter_swiper_null_safety: 1.0.2

  #图片保存
  image_gallery_saver: 2.0.2

  #json 动画
  lottie: 2.4.0

  permission_handler: 10.4.1

  pin_code_text_field: 1.8.0

  protobuf:
    git:
      url: https://github.com/dart-lang/protobuf
      path: protobuf

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #App 本地图片
  assets:
    - images/1.png
    - images/2.png
    - images/3.png

  module:
    androidX: false
    androidPackage: com.example.my_flutter
    iosBundleIdentifier: com.example.myFlutter
