name: my_flutter
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2

  flutter_is_emulator:
    git:
      url: https://github.com/g123k/flutter_is_emulator.git
      ref: 196d1b5ffdae04a74864bde432445b30776be46a

  image_gallery_saver: 1.6.8

  lottie: 0.7.0+1

  permission_handler: 5.1.0+2

  pin_code_text_field: 1.7.1

  protobuf:
    git:
      url: https://github.com/dart-lang/protobuf
      path: protobuf

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #App 本地图片
  assets:
    - images/1.png
    - images/2.png
    - images/3.png

  module:
    androidX: false
    androidPackage: com.example.my_flutter
    iosBundleIdentifier: com.example.myFlutter
