source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

use_frameworks!
inhibit_all_warnings!

#platform :ios, '9.0'

target 'EYDouYin' do

#pod 'AlicloudHTTPDNS', '~> 1.6.11'
pod 'ZFPlayer', '3.1.5'
pod 'ZFPlayer/ControlView', '~> 3.0'
pod 'ZFPlayer/AVPlayer', '~> 3.0'
#pod 'ZFPlayer/ijkplayer', '~> 3.0'

#pod 'MPMoviePlayerController-Subtitles', '~> 2.2.2'

pod 'AFNetworking', '3.2.1'         #网络请求
pod 'Alamofire', '4.8.0'            #网络请求
pod 'SwiftyJSON', '5.0.0'           # Swift 转 JSON
pod 'IQKeyboardManager', '6.3.0'    #键盘管理
pod 'SVProgressHUD', '2.2.5'        #提示框
pod 'YYModel', '1.0.4'              #字典转模型
pod 'YYCategories', '1.0.4'         #分类
pod 'YYCache', '1.0.4'              #缓存
pod 'MJRefresh', '3.2.0'            #刷新
pod 'MJExtension', '3.0.17'         #字典转模型
pod 'pop', '1.0.12'                 #动画
pod 'SDWebImage', '5.0.6'           #图片缓存
pod 'GKNavigationBarViewController', '2.3.2' #抖音的左滑 push 效果
#pod 'SJVideoPlayer', '2.5.7'       #播放器
pod 'Bugly', '2.5.0'                #Bugly
pod 'Masonry', '1.1.0'              #自动布局
pod 'SnapKit', '4.0.1'              #自动布局
pod 'TXLiteAVSDK_Player', '6.3.7088'
    # 腾讯云播放器-独立播放器
pod 'GDataXML-HTML', '1.4.1'        # 解析 XML/EXCEL
pod 'AliyunOSSiOS', '2.10.7'        # 阿里云 OSS
pod 'FMDB', '2.7.5'                 # 数据库存储
pod 'lottie-ios', '2.5.3'           # JSON 动画

#pod 'MWPhotoBrowser', '2.1.2'       # 图片浏览器(加载网络图片)8.6k
#pod 'IDMPhotoBrowser', '1.11.3'     # 图片浏览器(加载网络图片)2.7k
pod 'NYTPhotoViewer', '2.0.0'





#pragma mark - 微博(Swift 版本)
pod 'IJKMediaFramework', '0.1.2'
pod "Weibo_SDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git"

#pragma mark - React-Native
# 'node_modules'目录一般位于根目录中
# 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
# 如果你的RN版本 >= 0.42.0，则加入下面这行
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
'Core',
'RCTText',
'RCTNetwork',
'RCTWebSocket', # 这个模块是用于调试功能的
#'ART',
#'RCTActionSheet',
#'RCTGeolocation',
#'RCTImage',
#'RCTPushNotification',
#'RCTSettings',
#'RCTVibration',
#'RCTLinkingIOS',
#'BatchedBridge',
# 在这里继续添加你所需要的模块

'CxxBridge', # 如果RN版本 >= 0.47则加入此行
'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
'RCTAnimation' # FlatList和原生动画功能需要此模块
]


# 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

#pragma mark - Flutter
flutter_application_path = '../my_flutter/'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

end
