source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '10.0'

target 'EYDouYin' do

#pod 'AlicloudHTTPDNS', '~> 1.6.11'
pod 'ZFPlayer', '3.2.13'
pod 'ZFPlayer/ControlView', '~> 3.0'
pod 'ZFPlayer/AVPlayer', '~> 3.0'
# 因为项目中使用了 FFmpeg 和ijkplayer中使用的 FFmpeg 版本不同, 故不能同时存在,目前没有找到解决方案,暂时使用别的播放框架去实现
#pod 'ZFPlayer/ijkplayer', '~> 3.0'
#pod 'IJKMediaFramework', '0.1.2'

#pod 'MPMoviePlayerController-Subtitles', '~> 2.2.2'

pod 'AFNetworking', '4.0.1'         # 网络请求
pod 'Alamofire', '5.2.2'            # 网络请求
pod 'AliyunOSSiOS', '2.10.8'        # 阿里云 OSS
pod 'AvoidCrash', '2.5.2'           # 防止崩溃

pod 'BaiduMobStatCodeless', '5.2.6' # 百度无埋点 SDK
pod 'BAWKWebView', '1.0.9'          # 网页加载(Block 实现)
pod 'Bugly', '2.5.71'               # Bugly

pod 'FCUUID', '1.3.1'               # UUID(随机数)
pod 'FMDB', '2.7.5'                 # 数据库存储
pod 'FSCalendar', '2.8.1'           # 日历 8.8K OC/Swift
pod 'FSPagerView', '0.8.3'          # 轮播

pod 'GDataXML-HTML', '1.4.1'        # 解析 XML/EXCEL
pod 'GKNavigationBarViewController', '2.5.8' #抖音的左滑 push 效果
pod 'GRStarsView', '0.1.0'          # 星星评分view，支持小数，支持点击、拖动评分。

pod 'iflyMSC-ZW', '0.0.3'           # 科大讯飞
pod 'IQKeyboardManager', '6.5.6'    # 键盘管理
pod 'libOpenInstallSDK', '2.4.0'    # OpenInstall
pod 'lottie-ios', '2.5.3'           # JSON 动画(OC最高版本)

pod 'JTAppleCalendar','8.0.3'       # 日历 Swift 6.5K

pod 'LMJVerticalScrollText', '3.0.1'# 数字动画(没有使用)

pod 'KakaJSON', '1.1.2'             # 字典转模型
pod 'KJBannerView', '1.3.5'         # 图片轮播(网络加载)

pod 'Masonry', '1.1.0'              # 自动布局
pod 'MJExtension', '3.2.2'          # 字典转模型
pod 'MJRefresh', '3.5.0'            # 刷新

pod 'NSLogger', '1.9.7'             # 日志打印

pod 'PhotoSolution', '1.5.8'        # 多选图片
pod 'pop', '1.0.12'                 # 动画

pod 'Qiniu', '8.0.0'                # 七牛云上传

pod 'RJBadgeKit', '0.2.5'           # 小红点实现
pod 'RSKImageCropper', '2.3.0'      # 裁剪图片

pod 'SDWebImage', '5.9.0'           # 图片缓存
pod 'SFHFKeychainUtils', '1.0.0'    # 钥匙串访问
pod 'SnapKit', '5.0.1'              # 自动布局
pod 'SVProgressHUD', '2.2.5'        # 提示框
pod 'SwiftyJSON', '5.0.0'           # Swift 转 JSON

pod 'TXLiteAVSDK_Player', '7.7.9458' # 腾讯云播放器-独立播放器
pod 'TZImagePickerController', '3.4.2' #本地选择图片与视频
pod 'TwicketSegmentedControl', '0.1.2' # 分隔选中按钮

pod 'UICountingLabel', '1.4.1'        # 数字动画

pod 'WRNavigationBar', '1.2.0'        # 导航

pod 'XRCarouselView', '2.6.1'         # 图片轮播

pod 'YYModel', '1.0.4'                # 字典转模型
pod 'YYText', '1.0.7'                 # 富文本
pod 'YYCategories', '1.0.4'           # 分类
pod 'YYCache', '1.0.4'                # 缓存

pod 'ZYCornerRadius', '1.0.2'         # 切圆角

#pod 'SJVideoPlayer', '3.2.6'       #播放器
#pod 'MWPhotoBrowser', '2.1.2'       # 图片浏览器(加载网络图片)8.6k
#pod 'IDMPhotoBrowser', '1.11.3'     # 图片浏览器(加载网络图片)2.7k
#pod 'NYTPhotoViewer', '5.0.3'        # 不建议使用 没有直接设置网络地址去加载图片的方式只能自己处理图片加载然后更新界面





#pragma mark - 微博(Swift 版本)
pod "Weibo_SDK", '3.2.7'

#pragma mark - React-Native
# 'node_modules'目录一般位于根目录中
# 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
# 如果你的RN版本 >= 0.42.0，则加入下面这行
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
'Core',
'RCTText',
'RCTNetwork',
'RCTWebSocket', # 这个模块是用于调试功能的
#'ART',
#'RCTActionSheet',
#'RCTGeolocation',
#'RCTImage',
#'RCTPushNotification',
#'RCTSettings',
#'RCTVibration',
#'RCTLinkingIOS',
#'BatchedBridge',
# 在这里继续添加你所需要的模块

'CxxBridge', # 如果RN版本 >= 0.47则加入此行
'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
'RCTAnimation' # FlatList和原生动画功能需要此模块
]


# 如果RN版本 >= 0.45则加入下面三个第三方编译依赖
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

#pragma mark - Flutter
flutter_application_path = '../my_flutter/'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

end
